version: '3.9'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_APP_URL: http://localhost:3000
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      SUPABASE_URL: http://localhost:54321
      SUPABASE_ANON_KEY: change-me
      SUPABASE_SERVICE_ROLE_KEY: change-me
      OPENAI_API_KEY: ''
      REDIS_URL: redis://redis:6379
    depends_on:
      - db
      - redis
  db:
    image: supabase/postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
